# cat docker-compose.yml
version: '3.3'
services:
### MySQL Container
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER} # for Linux (not sure)
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306" 