"""empty message

Revision ID: 08c62574ebb6
Revises: 56743c9f9f89
Create Date: 2021-06-09 19:19:56.819624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c62574ebb6'
down_revision = '56743c9f9f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colony', sa.Column('name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('colony', sa.Column('locations', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colony', 'locations')
    op.drop_column('colony', 'name')
    # ### end Alembic commands ###
