"""empty message

Revision ID: 0d7628940b01
Revises: 08c62574ebb6
Create Date: 2021-06-09 19:37:28.896934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7628940b01'
down_revision = '08c62574ebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colonies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('locations', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('path', sa.String(length=100), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data_type', sa.String(length=25), nullable=True),
    sa.Column('video', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('colony')
    op.add_column('videos', sa.Column('file_name', sa.String(length=200), server_default='', nullable=False))
    op.add_column('videos', sa.Column('colony', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'videos', 'colonies', ['colony'], ['id'], ondelete='CASCADE')
    op.drop_column('videos', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('name', sa.VARCHAR(length=200), server_default=sa.text("('')"), nullable=False))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'colony')
    op.drop_column('videos', 'file_name')
    op.create_table('colony',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False),
    sa.Column('locations', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('video_data')
    op.drop_table('colonies')
    # ### end Alembic commands ###
