"""empty message

Revision ID: 1da80d6f9c49
Revises: 4a3b1d1f4682
Create Date: 2021-10-01 11:03:31.718880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1da80d6f9c49'
down_revision = '4a3b1d1f4682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_data_ibfk_2', 'video_data', type_='foreignkey')
    op.drop_constraint('video_data_ibfk_3', 'video_data', type_='foreignkey')
    op.drop_column('video_data', 'created_from_id')
    op.drop_column('video_data', 'created_by_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_data', sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_data', sa.Column('created_from_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('video_data_ibfk_3', 'video_data', 'video_data', ['created_from_id'], ['id'])
    op.create_foreign_key('video_data_ibfk_2', 'video_data', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
