"""added video metadata

Revision ID: 3a14a19fb9a7
Revises: 0d7628940b01
Create Date: 2021-06-10 14:31:37.681187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a14a19fb9a7'
down_revision = '0d7628940b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('frames', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('fps', sa.Numeric(), nullable=False))
    op.add_column('videos', sa.Column('realfps', sa.Numeric(), nullable=False))
    op.add_column('videos', sa.Column('filesize', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('hash', sa.String(length=70), nullable=False))
    op.add_column('videos', sa.Column('corrupted', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('trimmed', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframe0', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframe_1s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframe_2s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframe_10s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframeN_30s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframeN_2s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframeN_1s', sa.Boolean(), nullable=False))
    op.add_column('videos', sa.Column('hasframeN', sa.Boolean(), nullable=False))
    op.alter_column('videos', 'location',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'location',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('videos', 'hasframeN')
    op.drop_column('videos', 'hasframeN_1s')
    op.drop_column('videos', 'hasframeN_2s')
    op.drop_column('videos', 'hasframeN_30s')
    op.drop_column('videos', 'hasframe_10s')
    op.drop_column('videos', 'hasframe_2s')
    op.drop_column('videos', 'hasframe_1s')
    op.drop_column('videos', 'hasframe0')
    op.drop_column('videos', 'trimmed')
    op.drop_column('videos', 'corrupted')
    op.drop_column('videos', 'hash')
    op.drop_column('videos', 'filesize')
    op.drop_column('videos', 'realfps')
    op.drop_column('videos', 'fps')
    op.drop_column('videos', 'width')
    op.drop_column('videos', 'frames')
    # ### end Alembic commands ###
