"""empty message

Revision ID: 4a3b1d1f4682
Revises: a28c3c5a958c
Create Date: 2021-10-01 10:57:07.907392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3b1d1f4682'
down_revision = 'a28c3c5a958c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_data', sa.Column('created_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video_data', 'video_data', ['created_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_data', type_='foreignkey')
    op.drop_column('video_data', 'created_from_id')
    # ### end Alembic commands ###
