"""empty message

Revision ID: 56743c9f9f89
Revises: 52e4a560cd6b
Create Date: 2021-06-09 19:17:34.306335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56743c9f9f89'
down_revision = '52e4a560cd6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('path', sa.String(length=100), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('colony')
    # ### end Alembic commands ###
