"""empty message

Revision ID: 77b3b235c86b
Revises: be26837b8a1b
Create Date: 2021-06-30 09:44:34.309451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b3b235c86b'
down_revision = 'be26837b8a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ds_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ds_id'], ['data_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ds_id', 'video_id')
    )
    op.drop_table('colonies')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'videos', 'colonies', ['colony'], ['id'], ondelete='CASCADE')
    op.create_table('colonies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False),
    sa.Column('locations', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('video_data_set')
    op.drop_table('data_set')
    # ### end Alembic commands ###
