"""empty message

Revision ID: a28c3c5a958c
Revises: 
Create Date: 2021-10-01 10:55:31.509912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28c3c5a958c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_data', sa.Column('data', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'notes')
    op.drop_column('video_data', 'data')
    # ### end Alembic commands ###
