"""empty message

Revision ID: be05fbf2fc2b
Revises: 7cf4b33a9bd6
Create Date: 2021-10-08 11:46:06.500491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be05fbf2fc2b'
down_revision = '7cf4b33a9bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_data', sa.Column('created_from_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video_data', 'video_data', ['created_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_data', type_='foreignkey')
    op.drop_column('video_data', 'created_from_id')
    # ### end Alembic commands ###
