"""empty message

Revision ID: be26837b8a1b
Revises: da0a98c0eef9
Create Date: 2021-06-16 10:00:57.052042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be26837b8a1b'
down_revision = 'da0a98c0eef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'videos', ['file_name', 'path'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='unique')
    # ### end Alembic commands ###
