"""empty message

Revision ID: da0a98c0eef9
Revises: 3a14a19fb9a7
Create Date: 2021-06-10 14:39:33.364279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0a98c0eef9'
down_revision = '3a14a19fb9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'height')
    # ### end Alembic commands ###
